/**
 * En esta práctica deberás leer un archivo JSON y extraer todas las coincidencias de verduras 
 * que se encuentren dentro de él.
 * ! Deberás leer el archivo JSON
 * ! Obtener la información para después con una expresión regular filtrar los datos
 * ! Mostrar los datos en pantalla
 */


const verduras = {
  "SMAE": [
    {
      "Alimento": "Acelga cruda",
      "Categoría": "Verduras",
      "Cantidad": "2    ",
      "Unidad": "taza",
      "PesoBrutoG": "120",
      "PesoNetoG": "98",
      "EnergíaKcal": "22",
      "Proteína": "2.2",
      "Lípidos": "0.1",
      "Carbohidratos": "4.3",
      "Fibra": "3.6",
      "VitaminaAug": "310.9",
      "ÁcidoAscórbicomg": "29.5",
      "ÁcidoFólicoug": "14.8",
      "Hierromg": "2.5",
      "Potasiomg": "0",
      "IG": "64.0",
      "IC": "2.7",
      "AzucarPorEquivalenteG": "0",
      "Calciomg": "0",
      "Sodiomg": "0",
      "Forforomg": "0",
      "Selenioug": "0",
      "Colesterolmg": "0",
      "GrasaSaturadag": "0",
      "GrasaMonoinsaturadag": "0",
      "GrasaPoliinsaturadag": "0",
      "Etanolg": "0"
    },
    {
      "Alimento": "Acelga picada cocida",
      "Categoría": "Verduras",
      "Cantidad": " 0.5",
      "Unidad": "taza",
      "PesoBrutoG": "72",
      "PesoNetoG": "72",
      "EnergíaKcal": "19",
      "Proteína": "1.9",
      "Lípidos": "0.1",
      "Carbohidratos": "3.9",
      "Fibra": "2.1",
      "VitaminaAug": "275.8",
      "ÁcidoAscórbicomg": "17.9",
      "ÁcidoFólicoug": "10.1",
      "Hierromg": "1.4",
      "Potasiomg": "0",
      "IG": "64.0",
      "IC": "2.5",
      "AzucarPorEquivalenteG": "0",
      "Calciomg": "0",
      "Sodiomg": "0",
      "Forforomg": "0",
      "Selenioug": "0",
      "Colesterolmg": "0",
      "GrasaSaturadag": "0",
      "GrasaMonoinsaturadag": "0",
      "GrasaPoliinsaturadag": "0",
      "Etanolg": "0"
    },
    {
      "Alimento": "Alcachofa mediana cocida",
      "Categoría": "Verduras",
      "Cantidad": "1    ",
      "Unidad": "pieza",
      "PesoBrutoG": "120",
      "PesoNetoG": "48",
      "EnergíaKcal": "25",
      "Proteína": "1.4",
      "Lípidos": "0.2",
      "Carbohidratos": "5.7",
      "Fibra": "4.1",
      "VitaminaAug": "0.5",
      "ÁcidoAscórbicomg": "3.6",
      "ÁcidoFólicoug": "42.7",
      "Hierromg": "0.3",
      "Potasiomg": "0",
      "IG": "0",
      "IC": "0",
      "AzucarPorEquivalenteG": "0",
      "Calciomg": "0",
      "Sodiomg": "0",
      "Forforomg": "0",
      "Selenioug": "0",
      "Colesterolmg": "0",
      "GrasaSaturadag": "0",
      "GrasaMonoinsaturadag": "0",
      "GrasaPoliinsaturadag": "0",
      "Etanolg": "0"
    },
    {
      "Alimento": "Apio cocido",
      "Categoría": "Verduras",
      "Cantidad": " 0.75",
      "Unidad": "taza",
      "PesoBrutoG": "113",
      "PesoNetoG": "113",
      "EnergíaKcal": "20",
      "Proteína": "0.9",
      "Lípidos": "0.2",
      "Carbohidratos": "4.5",
      "Fibra": "1.8",
      "VitaminaAug": "29.3",
      "ÁcidoAscórbicomg": "6.9",
      "ÁcidoFólicoug": "24.8",
      "Hierromg": "0.5",
      "Potasiomg": "0",
      "IG": "0",
      "IC": "0",
      "AzucarPorEquivalenteG": "0",
      "Calciomg": "0",
      "Sodiomg": "0",
      "Forforomg": "0",
      "Selenioug": "0",
      "Colesterolmg": "0",
      "GrasaSaturadag": "0",
      "GrasaMonoinsaturadag": "0",
      "GrasaPoliinsaturadag": "0",
      "Etanolg": "0"
    },
    {
      "Alimento": "Apio crudo",
      "Categoría": "Verduras",
      "Cantidad": "1.5",
      "Unidad": "taza",
      "PesoBrutoG": "152",
      "PesoNetoG": "135",
      "EnergíaKcal": "22",
      "Proteína": "0.9",
      "Lípidos": "0.2",
      "Carbohidratos": "4.0",
      "Fibra": "2.5",
      "VitaminaAug": "29.7",
      "ÁcidoAscórbicomg": "4.2",
      "ÁcidoFólicoug": "48.5",
      "Hierromg": "0.3",
      "Potasiomg": "0",
      "IG": "0",
      "IC": "0",
      "AzucarPorEquivalenteG": "0",
      "Calciomg": "0",
      "Sodiomg": "0",
      "Forforomg": "0",
      "Selenioug": "0",
      "Colesterolmg": "0",
      "GrasaSaturadag": "0",
      "GrasaMonoinsaturadag": "0",
      "GrasaPoliinsaturadag": "0",
      "Etanolg": "0"
    },
    {
      "Alimento": "Arúgula, cruda",
      "Categoría": "Verduras",
      "Cantidad": "4    ",
      "Unidad": "taza",
      "PesoBrutoG": "80",
      "PesoNetoG": "80",
      "EnergíaKcal": "20",
      "Proteína": "2.1",
      "Lípidos": "0.5",
      "Carbohidratos": "2.9",
      "Fibra": "3.5",
      "VitaminaAug": "95.2",
      "ÁcidoAscórbicomg": "12.0",
      "ÁcidoFólicoug": "77.6",
      "Hierromg": "1.2",
      "Potasiomg": "0",
      "IG": "0",
      "IC": "0",
      "AzucarPorEquivalenteG": "0",
      "Calciomg": "0",
      "Sodiomg": "0",
      "Forforomg": "0",
      "Selenioug": "0",
      "Colesterolmg": "0",
      "GrasaSaturadag": "0",
      "GrasaMonoinsaturadag": "0",
      "GrasaPoliinsaturadag": "0",
      "Etanolg": "0"
    },
    {
      "Alimento": "Berenjena picada cocida",
      "Categoría": "Verduras",
      "Cantidad": "1    ",
      "Unidad": "taza",
      "PesoBrutoG": "99",
      "PesoNetoG": "99",
      "EnergíaKcal": "35",
      "Proteína": "0.8",
      "Lípidos": "0.2",
      "Carbohidratos": "8.6",
      "Fibra": "2.5",
      "VitaminaAug": "2.0",
      "ÁcidoAscórbicomg": "1.3",
      "ÁcidoFólicoug": "13.9",
      "Hierromg": "0.4",
      "Potasiomg": "0",
      "IG": "0",
      "IC": "0",
      "AzucarPorEquivalenteG": "0",
      "Calciomg": "0",
      "Sodiomg": "0",
      "Forforomg": "0",
      "Selenioug": "0",
      "Colesterolmg": "0",
      "GrasaSaturadag": "0",
      "GrasaMonoinsaturadag": "0",
      "GrasaPoliinsaturadag": "0",
      "Etanolg": "0"
    },
    {
      "Alimento": "Berro crudo",
      "Categoría": "Verduras",
      "Cantidad": "2    ",
      "Unidad": "taza",
      "PesoBrutoG": "68",
      "PesoNetoG": "56",
      "EnergíaKcal": "34",
      "Proteína": "1.3",
      "Lípidos": "0.1",
      "Carbohidratos": "0.7",
      "Fibra": "0.3",
      "VitaminaAug": "46.3",
      "ÁcidoAscórbicomg": "6.7",
      "ÁcidoFólicoug": "35.7",
      "Hierromg": "1.2",
      "Potasiomg": "0",
      "IG": "0",
      "IC": "0",
      "AzucarPorEquivalenteG": "0",
      "Calciomg": "0",
      "Sodiomg": "0",
      "Forforomg": "0",
      "Selenioug": "0",
      "Colesterolmg": "0",
      "GrasaSaturadag": "0",
      "GrasaMonoinsaturadag": "0",
      "GrasaPoliinsaturadag": "0",
      "Etanolg": "0"
    }
  ]
};



const datos = verduras.SMAE.filter((element) => /\bpicada\b/.test(element.Alimento))

datos.forEach((element) => console.log(element.Alimento))

/* const datos = verduras.SMAE.map(nombre => nombre.Alimento)

const regexp = /(\w|\s)*picada(\w|\s)* /g
let match

while ((match = regexp.exec(datos))) {
  console.log(match[0]); 
}*/